include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "bin/cache/**"
    # the following two are relative to the stocks example and the flutter package respectively
    # see https://github.com/dart-lang/sdk/issues/28463
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Util classes are awesome!
#    avoid_classes_with_only_static_members: false

    sort_constructors_first: false

    public_member_api_docs: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false  

    prefer_double_quotes: false

    constant_identifier_names: false

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Use parameter order as in json response
    always_put_required_named_parameters_first: true

    